name: Bump version on PR merge
on:
  pull_request:
    branches:
      - main
    types: closed

permissions:
  contents: write
  actions: write

  
jobs:
  update_version:
    if: github.event.pull_request.merged == true
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # Fetch full depth, otherwise the last step overwrites the last commit's parent, essentially removing the graph.
          fetch-depth: 0
          persist-credentials: false # This is important if you have branch protection rules!

      - name: Run bump_version.sh
        run: |
          bash ./bump_version.sh

      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
        
      - name: Amend the last commit
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git commit -a --amend --no-edit
          git push --force-with-lease
          echo "Complete"
